### ISSUE TITLE
Scenarios names with <variable> of a scenario outline show <variable> in the test explorer

### ISSUE THREAD

**Issue by kappa10j** [jimasp/behave-vsc#44] opened 2023-10-19 13:43 UTC
I have a scenario outline as such:

Scenario Outline: Schedule an Unplanned Default infrastructure team Change Request for < | Configuration Item |>"
   
    Examples:
      | Configuration Item |
      | Google Chrome      |
      | Active Directory   |

Instead of seeing 2 tests in the test explorer, I see one: 
"Schedule an Unplanned Default infrastructure team Change Request for < | Configuration Item |>"

I expect to see:
Schedule an Unplanned Default infrastructure team Change Request for Google Chrome
Schedule an Unplanned Default infrastructure team Change Request for Active Directory

fyi: I dont see | Configuration Item |, I see Configuration Item but with it wouldn't show as text.

python 3.10.2
Behave VSC v0.6.4
Package                 Version
----------------------- ---------
allure-behave           2.13.2
allure-python-commons   2.13.2
async-generator         1.10
atomicwrites            1.4.0
attrs                   21.4.0
autopep8                1.6.0
behave                  1.2.6
behavex                 3.0.0
certifi                 2021.10.8
cffi                    1.15.0
charset-normalizer      2.0.12
colorama                0.4.4
configobj               5.0.6
cryptography            36.0.1
csscompressor           0.9.5
exceptiongroup          1.1.3
extras                  1.0.0
fixtures                3.0.0
fuzzywuzzy              0.18.0
glob2                   0.7
greenlet                1.1.2
h11                     0.13.0
htmlmin                 0.1.12
idna                    3.3
iniconfig               1.1.1
Jinja2                  3.0.3
Mako                    1.1.6
MarkupSafe              2.0.1
mock                    4.0.3
numpy                   1.22.2
outcome                 1.1.0
packaging               21.3
pandas                  1.4.1
parse                   1.19.0
parse-type              0.6.0
pbr                     5.8.0
pip                     23.3
pluggy                  1.0.0
py                      1.11.0
pycodestyle             2.8.0
pycparser               2.21
pymssql                 2.2.4
pyOpenSSL               21.0.0
pyparsing               3.0.7
pypiwin32               223
PySocks                 1.7.1
pytest                  7.2.2
pytest-bdd              6.1.1
python-dateutil         2.8.2
python-subunit          1.4.0
pytz                    2021.3
pywin32                 303
requests                2.27.1
requests-negotiate-sspi 0.5.2
selenium                4.1.2
setuptools              60.5.0
six                     1.16.0
sniffio                 1.2.0
sortedcontainers        2.4.0
SQLAlchemy              1.4.31
sure                    2.0.0
testtools               2.5.0
toml                    0.10.2
tomli                   2.0.0
trio                    0.19.0
trio-websocket          0.9.2
typing_extensions       4.8.0
urllib3                 1.26.8
wsproto                 1.0.0

**Comment by jimasp** [comment] 2023-10-20 06:34
this looks like a duplicate of this feature request: https://github.com/jimasp/behave-vsc/issues/21 to have separate test tree nodes for examples.

(i implemented it a while back, but it needs a lot of testing and i've not got around to it yet)

**Comment by kappa10j** [comment] 2023-10-20 09:25
Thanks.  I really like this plugin.

**Closed as not planned** 2023-10-21 09:23 UTC
Labels: duplicate
